package ledger

import "testing"

func TestFingerprint_whenParamsCarryALoneSurrogate(t *testing.T) {
	// Given: request JSON whose string holds a lone surrogate, and Python's fingerprint of it
	// (goldens.txt, generated by Ledger._fingerprint for {"text": "\ud800"}).
	const python = "6d6b8fa2996301d38a6500c38ec5746907f90684f19d6a9c9a5e09f24e6d9d81"
	decoded, err := DecodeJSON([]byte(`{"text":"\ud800"}`))
	if err != nil {
		t.Fatal(err)
	}
	// When: the decoded params are fingerprinted.
	actual, err := Fingerprint("create_thread", decoded.(map[string]any))
	if err != nil {
		t.Fatal(err)
	}
	// Then: it is Python's hash, not the hash of U+FFFD that encoding/json would produce.
	replaced, _ := Fingerprint("create_thread", map[string]any{"text": "\ufffd"})
	if actual != python || actual == replaced {
		t.Fatalf("got %s (U+FFFD form %s)", actual, replaced)
	}
}

func TestFingerprint_whenAnAbsentRoleBecomesAnExplicitNull(t *testing.T) {
	// Given: the create_thread params from test_execution.py, with and without "role": None.
	base := map[string]any{"cwd": "/w", "sandbox": "read-only", "model": "anthropic/claude-opus-5-5", "reasoning_effort": "xhigh"}
	withNull := map[string]any{"role": nil}
	for k, v := range base {
		withNull[k] = v
	}
	// When: both are fingerprinted.
	absent, err := Fingerprint("create_thread", base)
	if err != nil {
		t.Fatal(err)
	}
	explicit, err := Fingerprint("create_thread", withNull)
	if err != nil {
		t.Fatal(err)
	}
	// Then: they differ, so omitting an unnamed role is what keeps old receipts replayable.
	if absent == explicit {
		t.Fatal("an explicit null role hashed like an absent one")
	}
}
