// Command generate writes printable_generated.go: the characters str.isprintable() accepts under
// the Unicode database of the CPython the port is compared with, read from that interpreter
// (`go generate ./internal/bridge/settings`, with python3 on PATH being CPython 3.14).
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
)

// version is the unicodedata.unidata_version the table is pinned to: CPython 3.14's.
const version = "16.0.0"

// script lists the runs of code points str.isprintable() accepts. A lone surrogate is refused.
const script = `
import json, sys, unicodedata
runs, start = [], None
for c in range(0x110000):
    printable = not 0xd800 <= c <= 0xdfff and chr(c).isprintable()
    if printable and start is None:
        start = c
    elif not printable and start is not None:
        runs.append((start, c - 1))
        start = None
if start is not None:
    runs.append((start, 0x10ffff))
json.dump({"version": unicodedata.unidata_version, "runs": runs}, sys.stdout)
`

func main() {
	out, err := exec.Command("python3", "-c", script).Output()
	if err != nil {
		fail(err)
	}
	var answer struct {
		Version string     `json:"version"`
		Runs    [][2]int32 `json:"runs"`
	}
	if err := json.Unmarshal(out, &answer); err != nil {
		fail(err)
	}
	if answer.Version != version {
		fail(fmt.Errorf("python3 has Unicode %s; the table is CPython 3.14's %s", answer.Version, version))
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/bridge/settings/generate from CPython 3.14's unicodedata %s; DO NOT EDIT.\n\n", version)
	b.WriteString("package settings\n\nimport \"unicode\"\n\n")
	fmt.Fprintf(&b, "// printableVersion is the unicodedata.unidata_version pythonPrintable was read from.\nconst printableVersion = %q\n\n", version)
	b.WriteString("// pythonPrintable is every character str.isprintable() accepts under that database.\n")
	b.WriteString("var pythonPrintable = &unicode.RangeTable{\n\tR16: []unicode.Range16{\n")
	latin := 0
	for _, run := range answer.Runs {
		if run[1] <= 0xffff {
			fmt.Fprintf(&b, "\t\t{0x%04x, 0x%04x, 1},\n", run[0], run[1])
			if run[1] <= unicodeMaxLatin1 {
				latin++
			}
		} else if run[0] <= 0xffff {
			fail(fmt.Errorf("a run crosses U+FFFF: %x-%x", run[0], run[1]))
		}
	}
	b.WriteString("\t},\n\tR32: []unicode.Range32{\n")
	for _, run := range answer.Runs {
		if run[0] > 0xffff {
			fmt.Fprintf(&b, "\t\t{0x%05x, 0x%05x, 1},\n", run[0], run[1])
		}
	}
	fmt.Fprintf(&b, "\t},\n\tLatinOffset: %d,\n}\n", latin)
	source, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("printable_generated.go", source, 0o644); err != nil {
		fail(err)
	}
}

const unicodeMaxLatin1 = 0xff

func fail(err error) {
	fmt.Fprintln(os.Stderr, "generate:", err)
	os.Exit(1)
}
