package hook

import (
	"bufio"
	"context"
	"encoding/hex"
	"encoding/json"
	"net"
	"os"
	"syscall"
	"testing"
	"time"
	"unicode/utf8"

	"golang.org/x/sys/unix"

	"github.com/thisisjun786/codex-relay-workflow/internal/testsupport/golden"
)

// socketPair is a connected pair of stream sockets: the owner's end and the peer's.
func socketPair(t *testing.T) (owner, peer *net.UnixConn) {
	t.Helper()
	// Darwin has no SOCK_CLOEXEC: mark both ends close-on-exec under ForkLock instead, so a
	// concurrent exec inherits neither.
	syscall.ForkLock.RLock()
	fds, err := unix.Socketpair(unix.AF_UNIX, unix.SOCK_STREAM, 0)
	if err == nil {
		unix.CloseOnExec(fds[0])
		unix.CloseOnExec(fds[1])
	}
	syscall.ForkLock.RUnlock()
	if err != nil {
		t.Fatal(err)
	}
	ends := make([]*net.UnixConn, 2)
	for i, fd := range fds {
		file := os.NewFile(uintptr(fd), "control-pair")
		conn, err := net.FileConn(file)
		_ = file.Close()
		if err != nil {
			t.Fatal(err)
		}
		ends[i] = conn.(*net.UnixConn)
	}
	return ends[0], ends[1]
}

// PR #185 4128954449 review: the owner reads a request as control.py _answer reads it. Over a
// corpus of frames (testdata/fixtures/control-frames.json, generated by the retired
// control_frames.py), HandleControl answers each with the line its golden holds, which began as
// the line the retained Python owner answered: the bytes decoded as json.loads decodes bytes (a
// UTF-8 byte order mark skipped, UTF-16 and UTF-32 detected, a lone surrogate passed and kept as
// the one character it is), and the deadline read as CPython 3.13's datetime.fromisoformat reads
// it (every date, separator, time and offset form, a naive value's TypeError, the fields' range
// errors in 3.13's words). A request admitted past its deadline is answered with owner_paths'
// refusal, so the corpus evaluates nothing.
func TestControlReadsEveryFrameAsControlPyReadsIt(t *testing.T) {
	root, state := t.TempDir(), t.TempDir()
	t.Setenv("CODEX_SESSION_RELAY_MARKER_ROOT", root)
	var corpus []struct{ Name, Frame string }
	if err := json.Unmarshal(golden.Fixture(t, "control-frames.json"), &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus) < 1000 {
		t.Fatalf("a corpus of %d frames", len(corpus))
	}
	answers := make([]frameAnswer, len(corpus))
	for i, c := range corpus {
		frame, err := hex.DecodeString(c.Frame)
		if err != nil {
			t.Fatal(err)
		}
		owner, peer := socketPair(t)
		ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
		done := make(chan error, 1)
		go func() { done <- HandleControl(ctx, owner, state) }()
		if err = peer.SetDeadline(time.Now().Add(5 * time.Second)); err != nil {
			t.Fatal(err)
		}
		if _, err = peer.Write(frame); err != nil {
			t.Fatal(err)
		}
		if err = peer.CloseWrite(); err != nil {
			t.Fatal(err)
		}
		got, _ := bufio.NewReader(peer).ReadBytes('\n')
		_ = peer.Close()
		if err = <-done; err != nil {
			t.Errorf("%s: the handler failed: %v", c.Name, err)
		}
		cancel()
		answers[i] = frameAnswer{Name: c.Name, Answer: string(got)}
		if !utf8.Valid(got) {
			answers[i] = frameAnswer{Name: c.Name, AnswerHex: hex.EncodeToString(got)}
		}
	}
	// The owner's answers, each with the state directory and marker root spelled <STATE> and
	// <ROOT>, compared frame by frame.
	raw := golden.Want(t, "answers", func() []byte {
		encoded, err := golden.Encode(answers)
		if err != nil {
			t.Fatal(err)
		}
		return encoded
	}, golden.Substitute(state, "<STATE>"), golden.Substitute(root, "<ROOT>"))
	var expected []frameAnswer
	if err := json.Unmarshal(raw, &expected); err != nil {
		t.Fatal(err)
	}
	if len(expected) != len(answers) {
		t.Fatalf("the golden holds %d answers, the corpus %d frames", len(expected), len(answers))
	}
	differ := 0
	for i, got := range answers {
		if got != expected[i] {
			if differ++; differ <= 40 {
				t.Errorf("%s: the owner answered %+v where the golden holds %+v", got.Name, got, expected[i])
			}
		}
	}
	if differ > 0 {
		t.Fatalf("%d of %d frames answered otherwise", differ, len(answers))
	}
}

// frameAnswer is the line the owner answered a frame with: as text, or in hex when it is not UTF-8.
type frameAnswer struct {
	Name      string `json:"name"`
	Answer    string `json:"answer,omitempty"`
	AnswerHex string `json:"answerHex,omitempty"`
}
