"""Verbatim blocks from the REAL Linear document, captured during the JUN-93 round trip.

Not hand-written escaping. MANGLED is what the connector made of a plain-text summary:
a bare filename autolinked, brackets and asterisks escaped. CONFIRMED is the same job
after the summary was wrapped in a fenced literal block, which came back byte-for-byte,
including the blank line the connector inserts before the end marker.
"""

SYNC_ID = 'fee894364cfcbdcd50f3e64b7535ab08'

RAW_SUMMARY = 'JUN-93 · 01a0a32e-c027-7ab2-804c-e239ed3db649 · needs_changes\ngeneration 1, revision 5dcde279ac43\na revision request was queued to the same child under generation 2\nfindings:\n  latest: verified — 0 failures. Exercised 24 hand fixtures, all 120 permutations of a tie-free multiset with identical output every time, interleaved multi-sensor cases and 400 seeded randomized cases. readings.py line 36 keeps the largest timestamp per sensor and the per-sensor best dict keeps sensors independent.\n  tie: needs_changes — 73 failures. Minimal witness tie_two: [{sensor a, timestamp 1, value 10},{sensor a, timestamp 1, value 20}] returned {a: 10} where acceptance requires {a: 20}. Reverse order tie_two_rev fails symmetrically, returning 20 where 10 is required, so this is the tie rule itself and not one ordering. Also fails tie_three, tie_then_lower, tie_falsy and all six tied permutations. Cause: readings.py line 36 compares with strict timestamp > best[sensor][0], so an equal timestamp never displaces the record already held and the first of a tied group wins. Changing that comparison to >= is sufficient; nothing else in the function needs to move. The docstring at lines 21-24 and the comment at lines 34-35 state this first-wins policy explicitly and acknowledge it diverges from the registered criterion.\n  preserve: verified — 0 failures. Empty input returns an empty dict. Every input record was compared against an id-keyed deep copy using a bit-exact, key-order-sensitive comparison, including float, signed-zero, NaN and 2**53+1 fixtures, and none was mutated: the function writes only to its local best dict and builds a fresh dict at line 38. Output key set equals the sensor set exactly and values are the selected records values.'

MANGLED_BLOCK = '<!-- relay-sync:fee894364cfcbdcd50f3e64b7535ab08 -->\nsyncId: fee894364cfcbdcd50f3e64b7535ab08\nsubjectKind: verdict\nissueKey: JUN-93\nrelationshipId: rel-6bb7a7340dccd2ef\neventId: dcf7e19aedefc8936e226bd4dda855f5\nexecutionGeneration: 1\nrevisionHash: 5dcde279ac4329134814297812127cdf44f5102c7b469fb8650665f30a7413ed\ndisposition: needs_changes\nidentityDigest: fee894364cfcbdcd50f3e64b7535ab080c7d7e1c45c56107c6242f78423e0124\n\nJUN-93 · 01a0a32e-c027-7ab2-804c-e239ed3db649 · needs_changes\ngeneration 1, revision 5dcde279ac43\na revision request was queued to the same child under generation 2\nfindings:\n  latest: verified — 0 failures. Exercised 24 hand fixtures, all 120 permutations of a tie-free multiset with identical output every time, interleaved multi-sensor cases and 400 seeded randomized cases. [readings.py](<http://readings.py>) line 36 keeps the largest timestamp per sensor and the per-sensor best dict keeps sensors independent.\n  tie: needs_changes — 73 failures. Minimal witness tie_two: \\[{sensor a, timestamp 1, value 10},{sensor a, timestamp 1, value 20}\\] returned {a: 10} where acceptance requires {a: 20}. Reverse order tie_two_rev fails symmetrically, returning 20 where 10 is required, so this is the tie rule itself and not one ordering. Also fails tie_three, tie_then_lower, tie_falsy and all six tied permutations. Cause: [readings.py](<http://readings.py>) line 36 compares with strict timestamp > best\\[sensor\\]\\[0\\], so an equal timestamp never displaces the record already held and the first of a tied group wins. Changing that comparison to >= is sufficient; nothing else in the function needs to move. The docstring at lines 21-24 and the comment at lines 34-35 state this first-wins policy explicitly and acknowledge it diverges from the registered criterion.\n  preserve: verified — 0 failures. Empty input returns an empty dict. Every input record was compared against an id-keyed deep copy using a bit-exact, key-order-sensitive comparison, including float, signed-zero, NaN and 2\\*\\*53+1 fixtures, and none was mutated: the function writes only to its local best dict and builds a fresh dict at line 38. Output key set equals the sensor set exactly and values are the selected records values.\n<!-- /relay-sync:fee894364cfcbdcd50f3e64b7535ab08 -->'

CONFIRMED_BLOCK = '<!-- relay-sync:fee894364cfcbdcd50f3e64b7535ab08 -->\nsyncId: fee894364cfcbdcd50f3e64b7535ab08\nsubjectKind: verdict\nissueKey: JUN-93\nrelationshipId: rel-6bb7a7340dccd2ef\neventId: dcf7e19aedefc8936e226bd4dda855f5\nexecutionGeneration: 1\nrevisionHash: 5dcde279ac4329134814297812127cdf44f5102c7b469fb8650665f30a7413ed\ndisposition: needs_changes\nidentityDigest: fee894364cfcbdcd50f3e64b7535ab080c7d7e1c45c56107c6242f78423e0124\n\n```text\nJUN-93 · 01a0a32e-c027-7ab2-804c-e239ed3db649 · needs_changes\ngeneration 1, revision 5dcde279ac43\na revision request was queued to the same child under generation 2\nfindings:\n  latest: verified — 0 failures. Exercised 24 hand fixtures, all 120 permutations of a tie-free multiset with identical output every time, interleaved multi-sensor cases and 400 seeded randomized cases. readings.py line 36 keeps the largest timestamp per sensor and the per-sensor best dict keeps sensors independent.\n  tie: needs_changes — 73 failures. Minimal witness tie_two: [{sensor a, timestamp 1, value 10},{sensor a, timestamp 1, value 20}] returned {a: 10} where acceptance requires {a: 20}. Reverse order tie_two_rev fails symmetrically, returning 20 where 10 is required, so this is the tie rule itself and not one ordering. Also fails tie_three, tie_then_lower, tie_falsy and all six tied permutations. Cause: readings.py line 36 compares with strict timestamp > best[sensor][0], so an equal timestamp never displaces the record already held and the first of a tied group wins. Changing that comparison to >= is sufficient; nothing else in the function needs to move. The docstring at lines 21-24 and the comment at lines 34-35 state this first-wins policy explicitly and acknowledge it diverges from the registered criterion.\n  preserve: verified — 0 failures. Empty input returns an empty dict. Every input record was compared against an id-keyed deep copy using a bit-exact, key-order-sensitive comparison, including float, signed-zero, NaN and 2**53+1 fixtures, and none was mutated: the function writes only to its local best dict and builds a fresh dict at line 38. Output key set equals the sensor set exactly and values are the selected records values.\n```\n\n<!-- /relay-sync:fee894364cfcbdcd50f3e64b7535ab08 -->'
