package hook

import (
	"strings"
	"testing"
)

// worktreeDelCorpusRow is one command the worktree deletion guard is judged on, with the deny decision the shared
// reader gives it. The fixture paths are placeholders: {CHECKOUT} the checkout, {SLOT} the slot, {WORKTREES} the
// worktrees root, {OTHER} a neighbour directory, {HOME} the temporary home. The rows are the verdicts of the lexer
// suite this file replaces (CRW-1028 S3); the rows that changed on purpose are listed in worktreedel_changes_test.go.
type worktreeDelCorpusRow struct {
	cmd  string
	deny bool
}

func worktreeDelCorpusRows() []worktreeDelCorpusRow {
	return []worktreeDelCorpusRow{
		{"-x rm -rf ../repo", false},
		{"xargs rm -rf ../other", true},
		{"echo `echo safe; rm -rf '../repo\\\n'; echo done`", false},
		{"echo `x`; rm -rf '.\\\n'", false},
		{"rm -rf $'.\\\n'", true},
		{"echo a # c \\\nrm -rf ./build", true},
		{"(echo a)#c \\\nrm -rf ./build", true},
		{"echo \u003c\u003c'EOF'\n$'x\\'\nEOF\nrm -rf ../other\\\n; # '", true},
		{"echo a # ` \\\nrm -rf ../other", true},
		{"cat \u003c\\\n\u003cEOF\n$'x\\'\nEOF\nrm -rf ../other\\\n", true},
		{"\"$GO\" test ./...", true},
		{"$EDITOR notes.md", true},
		{"\"$RELAY\" --state /tmp/x show", true},
		{"bash -c 'echo $1' -c 'rm -rf ../repo'", false},
		{"printf 'rm -rf ../repo' | bash \u003c/dev/null", true},
		{"printf 'rm -rf ../repo' | bash \u003c /dev/null", true},
		{"printf 'rm -rf ../repo' | bash 0\u003c/dev/null", true},
		{"printf 'rm -rf ../repo' | bash 0\u003c /dev/null", true},
		{"printf 'echo hi' | bash \u003c/dev/null", true},
		{"printf 'rm -rf ../repo' ${x:- #} |\\nbash", false},
		{"printf x | # c\\ncat", true},
		{"printf 'rm -rf ../repo' ${x:-\"}\" #} |\\nbash", false},
		{"printf x | printf 'rm -rf ../repo' ${x:- #} |\\nbash", false},
		{"cd \\.\\.; rm -rf other", true},
		{"rm -rf $'\\x2e\\x2e/other'", true},
		{"rm -rf $'\\056\\056/other'", true},
		{"rm -rf $'\\u002e\\u002e/other'", true},
		{"rm -rf $'\\U0000002e./other'", true},
		{"rm -rf $'../other\\x00junk'", true},
		{"rm -rf $'../other\\400junk'", true},
		{"rm -rf $'../other\\c@junk'", true},
		{"rm -rf $'../ot\\c junk'her", true},
		{"rm -rf $'../other\\c`junk'", true},
		{"rm -rf $'../other\\cࠀjunk'", true},
		{"rm -rf $'\\U80000000../other'", true},
		{"rm -rf $'../ot\\Uffffffffher'", true},
		{"rm -rf $'../other\\U80000001'", true},
		{"rm -rf $'../repo\\x00junk'tail", true},
		{"rm -rf $'../repo\\x'", true},
		{"rm -rf $'../repo\\c'z", true},
		{"echo x # rm -rf /var/tmp/crw-1028/TestWorktreeDelQuoteKeepsEarlierDenies3313292908/001/.codex/worktrees/zk3q", false},
		{"$'s\\x68' -c 'r\\\nm -rf ../../other'", true},
		{"su --command 'rm -rf ../other' root", true},
		{"su --session-command 'rm -rf ../other' root", true},
		{"su --com='rm -rf ../other' root", true},
		{"su --se 'rm -rf ../other' root", true},
		{"bash -c $'rm\\t-rf\\t../other'", true},
		{"eval $'rm\\t-rf\\t../other'", true},
		{"sh -c $'echo a\\nrm -rf ../other'", true},
		{"bash -c '\u003c\u003c\u003cignored; rm -rf ../other'", true},
		{"bash -oc posix 'rm -rf ../other'", true},
		{"bash --rcfile /dev/null -c 'rm -rf ../other'", true},
		{"bash --init-file /dev/null -c 'rm -rf ../other'", true},
		{"zsh -oshwordsplit -c 'rm -rf ../other'", true},
		{"su --shell /bin/sh root", true},
		{"bash script.sh", true},
		{"rm -rf '.\\\n' # sh", true},
		{"rm -rf ./build-zk3q", false},
		{"rm /var/tmp/crw-1028/TestFallbackForUnresolvableTargets613980038/001/.codex/worktrees/zk3q/repo", false},
		{"find . -name zk3q | xargs rm -rf", true},
		{"rm -rf \"$X\" \u0026\u0026 echo cleaning", true},
		{"rd /var/tmp/crw-1028/TestFallbackForUnresolvableTargets613980038/001/.codex/worktrees/zk3q/repo", false},
		{"Remove-Item -Recurse -LiteralPath /var/tmp/crw-1028/TestFallbackForUnresolvableTargets613980038/001/.codex/worktrees/zk3q", false},
		{"REMOVE-ITEM /var/tmp/crw-1028/TestFallbackForUnresolvableTargets613980038/001/.codex/worktrees/zk3q/repo", false},
		{"git worKtree remove /var/tmp/crw-1028/TestFallbackForUnresolvableTargets613980038/001/.codex/worktrees/zk3q/repo", true},
		{"cd ..\nrm -rf other", true},
		{"cat \u003e clean.sh \u003c\u003c'EOF'\nrm -rf .\nEOF", false},
		{"echo \"rm -rf /var/tmp/crw-1028/TestExtendedWalkAddsDenies137562850/001/.codex/worktrees/zk3q\"", false},
		{"rm -rf ${TMPDIR}/x", true},
		{"source ./env.sh", true},
		{"bash script.sh \u003c\u003cEOF\n$X\nEOF", true},
		{"bash --rcfile \"$X\" script.sh", true},
		{"bash --init-file \"$X\" script.sh", true},
		{"Y=1 \"$GO\" test ./...", true},
		{"cat \u003c\u003cEOF; bash \u003c/dev/null\n$X\nEOF", true},
		{"bash script.sh \"$ARG\"", true},
		{"bash \"$SCRIPT\"", true},
		{"bash -c'rm -rf ../repo'", true},
		{"sh -c'rm -rf ../repo'", true},
		{"zsh -c'rm -rf ../repo'", true},
		{"su -sc'rm -rf ../repo' root", true},
		{"su -gc'rm -rf ../repo' root", true},
		{"su -c 'echo ok' root 'rm -rf ../repo'", true},
		{"su root -c 'echo ok' 'rm -rf ../repo'", true},
		{"su -lc'echo ok' root 'rm -rf ../repo'", true},
		{"su -s /bin/sh -c 'echo ok' root 'rm -rf ../repo'", true},
		{"ksh -c 'echo OK' 'rm -rf ../repo'", false},
		{"csh -c 'echo OK' 'rm -rf ../repo'", false},
		{"fish -c 'echo OK' 'rm -rf ../repo'", false},
		{"bash -c 'echo OK' \u003c\u003c\u003c 'rm -rf ../repo'", false},
		{"bash -c 'echo OK' \u003e 'log file' 'rm -rf ../repo'", false},
		{"echo \\\\\nrm -rf ../repo", true},
		{"echo a # c \\\nrm -rf ../repo", true},
		{"(echo a)#c \\\nrm -rf ../repo", true},
		{"rm -rf \".\\\n\"", true},
		{"echo $$'a\\'; rm -rf .\\\n; echo 'x' \\'", true},
		{"echo \u003c\u003c'EOF'\n$'x\\'\nEOF\nrm -rf ../repo\\\n; # '", true},
		{"cat \u003c\\\n\u003cEOF\n$'x\\'\nEOF\nrm -rf ../repo\\\n", true},
		{"echo `true`; echo \\\\\nrm -rf ../repo", true},
		{"echo \\\\\nrm -rf ../repo \u003c\u003cEOF\nx\nEOF", true},
		{"echo a # ` \\\nrm -rf ../repo", true},
		{"rm -rf '.\\\n'", false},
		{"echo \\\\\\\nrm -rf ../repo", false},
		{"rm -rf .\\\n/build", false},
		{"rm -rf \".\\\n/build\"", false},
		{"echo \\\\\nrm -rf ./build", false},
		{"echo $$'a\\'; rm -rf ./build\\\n; echo 'x' \\'", false},
		{"echo `echo safe; rm -rf '../other\\\n'; echo done`", false},
		{"echo `true`; echo \\\\\nrm -rf ../other", false},
		{"echo \\\\\nrm -rf ../other \u003c\u003cEOF\nx\nEOF", false},
		{"echo `x`; rm -rf './build\\\n'", false},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c'rm -rf ../repo'", true},
		{"su -c 'source /dev/stdin' root \u003c\u003c\u003c'rm -rf ../repo'", true},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c\"rm -rf ../repo\"", true},
		{"bash \u003c\u003c\u003c'rm -rf ../repo'", true},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c$'rm -rf ../repo'", true},
		{"cat \u003c\u003c\u003c'hello'", false},
		{"bash -c 'echo ok' \u003c\u003c\u003c'x'", false},
		{"cat \u003c\u003c\u003c'rm -rf ../repo'", false},
		{"echo \u003c\u003c\u003c'rm -rf ../repo'", false},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c 'rm -rf ../repo'", true},
		{"su -c 'source /dev/stdin' root \u003c\u003c\u003c 'rm -rf ../repo'", true},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c \"rm -rf ../repo\"", true},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c $'rm -rf ../repo'", true},
		{"bash \u003c\u003c\u003c 'rm -rf ../repo'", true},
		{"cat \u003c\u003c\u003c 'hello'", false},
		{"bash -c 'echo ok' \u003c\u003c\u003c 'x'", false},
		{"bash -c 'echo ok' \u003c\u003c\u003c'rm -rf ../repo'", false},
		{"bash -c 'echo ok' \u003c\u003c\u003c 'rm -rf ../repo'", false},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c'rm -rf ../other'", true},
		{"bash -c 'source /dev/stdin' \u003c\u003c\u003c 'rm -rf ../other'", true},
		{"$(printf 'rm -rf ../repo')", true},
		{"`printf 'rm -rf ../repo'`", true},
		{"X=rm; $X -rf ../repo", true},
		{"\"$X\" -rf ../repo", true},
		{"${X} -r ../repo", true},
		{"bash -c '$X -rf ../repo'", true},
		{"bash \u003c\u003c'EOF'\n$X -rf ../repo\nEOF", true},
		{"X=rm; echo $X", false},
		{"bash -c 'echo OK' \"$(rm -rf ../repo)\"", true},
		{"bash -c 'echo OK' \"`rm -rf ../repo`\"", true},
		{"sh -c 'true' x \"$(rm -rf ../repo)\"", true},
		{"sh -c 'echo OK' x \"$(rm -rf ../repo)\"", true},
		{"bash -c 'echo OK' \u003c(rm -rf ../repo)", true},
		{"cd \"$(rm -rf ../repo; pwd)\"", true},
		{"echo `true`#`rm -rf ../repo`", true},
		{"echo \"`# '`\"; rm -rf ../repo", true},
		{"echo \"`'`\"; rm -rf ../repo", true},
		{": \"$($()#)\"; r\\m -r ../repo", true},
		{"echo \"$(echo ${x:-)}; rm -rf ../repo)\"", true},
		{"echo \"$(echo ${x}#)\"; rm -rf ../repo", true},
		{"bash -c 'echo OK' \"$(echo \")\"; rm -rf ../repo)\"", true},
		{"echo \"$(case x in x) : ;; esac; rm -rf ../repo)\"", true},
		{"bash -c 'echo OK' -c 'rm -rf ../repo'", false},
		{"bash -c 'echo OK' '$(rm -rf ../repo)'", false},
		{"bash -c 'echo OK' \"$(rm -rf ../other)\"", false},
		{"bash -c 'echo OK' \"$(rm -rf ./build)\"", false},
		{"echo \"$(rm -rf ../other)\"", false},
		{"bash -c 'eval \"$0\"' 'rm -rf ../repo'", true},
		{"bash -c 'eval `printf \"\\x24\\x31\"`' -c 'rm -rf ../repo'", true},
		{"bash -c 'declare -p | grep \"^declare -a BASH_AR.V=\" | cut -d\\\" -f2 | bash' -c 'rm -rf ../repo'", true},
		{"su -c 'echo ok' -c 'rm -rf ../repo' root", true},
		{"echo `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true`", false},
		{"echo \"`true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` \"", false},
		{"echo `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true`; rm -rf ../repo", true},
		{"echo \"`true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` `true` \"; rm -rf ../repo", true},
		{"echo $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true) $(true)", false},
		{"printf 'rm -rf ../repo' | bash \u003c\u00260", true},
		{"printf 'rm -rf ../repo' | bash 0\u003c\u00260", true},
		{"printf 'rm -rf ../repo' | bash \u003c\u00262", true},
		{"printf 'rm -rf ../repo' | bash 0\u003c\u00262", true},
		{"printf 'rm -rf ../repo' | bash \u003c\u0026-", true},
		{"printf 'rm -rf ../repo' | bash 0\u003c\u0026-", true},
		{"printf 'rm -rf ../repo' | bash 2\u003c/dev/null", true},
		{"printf 'rm -rf ../repo' | (true; bash)", true},
		{"printf 'rm -rf ../repo' | (cd sub; bash)", true},
		{"printf 'rm -rf ../repo' | ( exec 2\u003e/dev/null; bash )", true},
		{"printf 'rm -rf ../repo' | (cd sub \u0026\u0026 bash)", true},
		{"printf 'rm -rf ../repo' | { bash; }", true},
		{"printf 'rm -rf ../repo' | { cd sub; bash; }", true},
		{"printf 'rm -rf ../repo' | (bash)", true},
		{"printf 'rm -rf ../repo' | ( sh )", true},
		{"printf x | (cd sub; cat)", false},
		{"printf x | { cat; }", false},
		{"printf x | (bash -c 'cat')", false},
		{"printf 'rm -rf ../repo' | nohup bash", true},
		{"printf 'rm -rf ../repo' | timeout 5 bash", true},
		{"printf 'rm -rf ../repo' | setsid bash", true},
		{"printf 'rm -rf ../repo' | nice bash", true},
		{"printf 'rm -rf ../repo' | stdbuf -o0 bash", true},
		{"printf 'rm -rf ../repo' | exec bash", true},
		{"printf 'rm -rf ../repo' | time bash", true},
		{"printf 'rm -rf ../repo' | env bash", true},
		{"printf 'rm -rf ../repo' | command bash", true},
		{"printf 'rm -rf ../repo' | sudo bash", true},
		{"printf 'rm -rf ../repo' | xargs bash", true},
		{"printf 'rm -rf ../repo' | ionice bash", true},
		{"printf 'rm -rf ../repo' | builtin bash", true},
		{"printf x | nohup cat", false},
		{"printf x | timeout 5 cat", false},
		{"printf x | nice cat", false},
		{"nohup rm -rf ../repo", true},
		{"nohup rm -rf ../other", false},
		{"timeout 5 rm -rf ../repo", true},
		{"timeout 5 rm -rf ../other", false},
		{"nice rm -rf ../repo", true},
		{"nice rm -rf ../other", false},
		{"nice -n 5 rm -rf ../repo", true},
		{"nice -n 5 rm -rf ../other", false},
		{"setsid rm -rf ../repo", true},
		{"setsid rm -rf ../other", false},
		{"stdbuf -o0 rm -rf ../repo", true},
		{"stdbuf -o0 rm -rf ../other", false},
		{"ionice rm -rf ../repo", true},
		{"ionice rm -rf ../other", false},
		{"xargs rm -rf ../repo", true},
		{"exec rm -rf ../repo", true},
		{"exec rm -rf ../other", false},
		{"printf 'rm -rf ../repo' | (bash) 2\u003e/dev/null", true},
		{"printf 'rm -rf ../repo' | (bash) \u003e/dev/null", true},
		{"printf 'rm -rf ../repo' | (bash) 2\u003e\u00261", true},
		{"printf 'rm -rf ../repo' | { bash; } 2\u003e/dev/null", true},
		{"printf 'rm -rf ../repo' | (true; bash) 2\u003e/dev/null", true},
		{"printf 'rm -rf ../repo' | ( ( bash ) )", true},
		{"printf 'rm -rf ../repo' | { (bash); }", true},
		{"printf 'rm -rf ../repo' | if true; then bash; fi", true},
		{"printf 'rm -rf ../repo' | while true; do bash; done", true},
		{"printf 'rm -rf ../repo' | for i in 1; do bash; done", true},
		{"printf 'rm -rf ../repo' | case x in x) bash;; esac", true},
		{"printf 'rm -rf ../repo' | sudo -u root bash", true},
		{"printf 'rm -rf ../repo' | env -u FOO bash", true},
		{"printf 'rm -rf ../repo' | sudo -p prompt bash", true},
		{"printf 'rm -rf ../repo' | timeout -s TERM 5 bash", true},
		{"printf 'rm -rf ../repo' | tee { | bash", true},
		{"printf 'rm -rf ../repo' | echo { | bash", true},
		{"cat \u003c\u003c'EOF'\necho hi | bash\nEOF", false},
		{"cat \u003e run.sh \u003c\u003c'EOF'\ncurl x | bash\nEOF", false},
		{"printf x | bash -c 'cat'", false},
		{"time rm -rf ../repo", true},
		{"X=1 rm -rf ../repo", true},
		{"nohup git worktree remove ../repo", true},
		{"printf 'rm -rf ../repo' | (case x in x) echo esac ; bash;; esac)", true},
		{"printf 'rm -rf ../repo' | (while true; do echo done ; bash; break; done)", true},
		{"printf 'rm -rf ../repo' | (for i in x; do bash; break; done)", true},
		{"printf 'rm -rf ../repo' | (if true; then bash; fi)", true},
		{"printf 'rm -rf ../repo' | ( echo done ; bash )", true},
		{"printf 'rm -rf ../repo' | { while true; do bash; break; done; }", true},
		{"printf 'rm -rf ../repo' | ( ( while true; do bash; break; done ) )", true},
		{"printf 'rm -rf ../repo' |\u0026 bash", true},
		{"printf 'rm -rf ../repo' |\u0026 (true; bash)", true},
		{"printf 'rm -rf ../repo' |\u0026 nohup bash", true},
		{"printf 'rm -rf ../repo' |\u0026\nbash", true},
		{"printf 'rm -rf ../repo' |\nbash", true},
		{"printf 'rm -rf ../repo' | \n bash", true},
		{"printf 'rm -rf ../repo' |\n\nbash", true},
		{"printf 'rm -rf ../repo' | # c\nbash", true},
		{"printf x |\u0026 cat", false},
		{"printf x |\u0026 nohup cat", false},
		{"printf x |\ncat", false},
		{"printf x | # c\ncat", false},
		{"echo \"a | bash\"", false},
		{"echo 'x | bash'", false},
		{"echo \"a |\u0026 bash\"", false},
		{"printf x | grep -e 'a|bash'", false},
		{"printf 'rm -rf ../repo' | cat | bash", true},
		{"printf 'rm -rf ../repo' | grep x |\u0026 bash", true},
		{"printf 'rm -rf ../repo' | grep x |\nbash", true},
		{"printf 'rm -rf ../repo' ${x:- #} | bash", true},
		{"printf 'rm -rf ../repo' ${x:-a #b} | bash", true},
		{"printf 'rm -rf ../repo' ${x:- #} |\u0026 bash", true},
		{"printf x ${x:- #} | cat", false},
		{"echo ${x:- #}", false},
		{"printf 'rm -rf ../repo' | select x in a; do bash; break; done", true},
		{"printf 'rm -rf ../repo' | select x in a\ndo bash\ndone", true},
		{"printf 'rm -rf ../repo' | select x; do bash; done", true},
		{"printf x | select y in a; do cat; break; done", false},
		{"printf x | select y in a; do echo $y; done", false},
		{"printf 'rm -rf ../repo' ${x:-\"}\" #} | bash", true},
		{"printf 'rm -rf ../repo' ${x:-a\"}\"b #} | bash", true},
		{"printf 'rm -rf ../repo' ${x:-\"}\" #} |\u0026 bash", true},
		{"printf x | printf 'rm -rf ../repo' ${x:- #} | bash", true},
		{"printf x | printf 'rm -rf ../repo' ${x:- #} |\u0026 bash", true},
		{"printf x | echo 'rm -rf ../repo' ${x:- #b} | bash", true},
		{"printf 'rm -rf ../repo' | cat ${x:- #} | bash", true},
		{"printf x ${y:-a | bash } | cat", false},
		{"printf x | printf 'rm -rf ../repo' ${x:- #} | cat", false},
		{"echo ${x:-a | bash}", false},
		{"printf 'rm -rf ../repo' ${x:-$(echo }) #} | bash", true},
		{"printf 'rm -rf ../repo' ${x:-$(echo })} | bash", true},
		{"printf x | printf 'rm -rf ../repo' ${x:-$(echo }) #} | bash", true},
		{"printf 'rm -rf ../repo' ${x:-$(echo }) #} |\u0026 bash", true},
		{"echo ${x:-$(echo hi)}", false},
		{"echo ${x:- $(echo })}", false},
		{"printf 'rm -rf ../repo' ${q:-a{b} | bash", true},
		{"printf x | printf 'rm -rf ../repo' ${q:-a{b} | bash", true},
		{"printf 'rm -rf ../repo' ${q:-a{b} |\u0026 bash", true},
		{"printf 'rm -rf ../repo' ${x:-\\${y:- #\\}} | bash", true},
		{"echo ${q:-a{b}c}", false},
		{"printf x ${q:-a{b} | cat", false},
		{"echo a # it's\nrm -rf ../repo", true},
		{"echo a # it's\nrm -rf ../other", false},
		{"echo \\'\nrm -rf ../repo", true},
		{"echo \\'\nrm -rf ../other", false},
		{"echo \\\"\nrm -rf ../repo", true},
		{"echo \\\"\nrm -rf ../other", false},
		{"echo \"a\\\"b\"\nrm -rf ../repo", true},
		{"echo \"a\\\"b\"\nrm -rf ../other", false},
		{"rm -rf ..\\/repo", true},
		{"rm -rf ..\\/other", false},
		{"rm -rf \\.\\./repo", true},
		{"rm -rf \\.\\./other", false},
		{"rm -rf ../re\\po", true},
		{"rm -rf ../ot\\her", false},
		{"echo $'a\\'b'\nrm -rf ../repo", true},
		{"echo $'a\\'b'\nrm -rf ../other", false},
		{"rm -rf $'../repo'", true},
		{"rm -rf $'../other'", false},
		{"rm -rf $\"../repo\"", true},
		{"rm -rf $\"../other\"", false},
		{"echo a;# it's\nrm -rf ../repo", true},
		{"echo a;# it's\nrm -rf ../other", false},
		{"echo a\u0026# it's\nrm -rf ../repo", true},
		{"echo a\u0026# it's\nrm -rf ../other", false},
		{"(echo a)# it's\nrm -rf ../repo", true},
		{"(echo a)# it's\nrm -rf ../other", false},
		{"echo $(case x in x)# it's\nrm -rf ../repo ;; esac)", true},
		{"echo $(case x in x)# it's\nrm -rf ../other ;; esac)", false},
		{"{ # it's\nrm -rf ../repo; }", true},
		{"{ # it's\nrm -rf ../other; }", false},
		{"echo a # '; rm -rf ../other\nrm -rf ../repo", true},
		{"echo a # '; rm -rf ../repo\nrm -rf ../other", false},
		{"rm -rf \"../re\\po\"", false},
		{"rm -rf '..\\/repo'", false},
		{"rm -rf \"..\\/repo\"", false},
		{"rm -rf \"..\\\\/repo\"", false},
		{"echo \"a\\\\\"\nrm -rf ../repo", true},
		{"echo \"a\\\\\"\nrm -rf ../other", false},
		{"echo a # c\nrm -rf ../repo", true},
		{"echo a # c\nrm -rf ../other", false},
		{"echo \"a # b\" \u0026 rm -rf ../repo", true},
		{"echo \"a # b\" \u0026 rm -rf ./build", false},
		{"echo '#' \u0026 rm -rf ../repo", true},
		{"echo '#' \u0026 rm -rf ./build", false},
		{"echo ${x#y} \u0026 rm -rf ../repo", true},
		{"echo ${x#y} \u0026 rm -rf ./build", false},
		{"echo $# \u0026 rm -rf ../repo", true},
		{"echo $# \u0026 rm -rf ./build", false},
		{"echo a#b \u0026 rm -rf ../repo", true},
		{"echo a#b \u0026 rm -rf ./build", false},
		{"echo \\# \u0026 rm -rf ../repo", true},
		{"echo \\# \u0026 rm -rf ./build", false},
		{"echo ''# x \u0026 rm -rf ../repo", true},
		{"echo ''# x \u0026 rm -rf ./build", false},
		{"echo `x`# \u0026 rm -rf ../repo", true},
		{"echo `x`# \u0026 rm -rf ../other", false},
		{"# it's\nrm -rf ../repo", true},
		{"# it's\nrm -rf ../other", false},
		{"r\\m -rf ../repo", true},
		{"r\\m -rf ../other", false},
		{"cd \\.\\.; rm -rf repo", true},
		{"git -C \\.\\. worktree remove repo", true},
		{"git -C \\.\\. worktree remove other", false},
		{"rm -rf $'\\x2e\\x2e/repo'", true},
		{"rm -rf $'\\056\\056/repo'", true},
		{"rm -rf $'\\u002e\\u002e/repo'", true},
		{"rm -rf $'\\U0000002e./repo'", true},
		{"rm -rf $'../repo\\x00junk'", true},
		{"rm -rf $'../repo\\400junk'", true},
		{"rm -rf $'../repo\\c@junk'", true},
		{"rm -rf $'../re\\c junk'po", true},
		{"rm -rf $'../repo\\c`junk'", true},
		{"rm -rf $'../repo\\cࠀjunk'", true},
		{"rm -rf $'\\U80000000../repo'", true},
		{"rm -rf $'../re\\Uffffffffpo'", true},
		{"rm -rf $'../repo\\U80000001'", true},
		{"echo `#it's`\nrm -rf ../repo", true},
		{"echo `#it's`\nrm -rf ../other", false},
		{"echo `#x'`; rm -rf ../repo", true},
		{"echo `#x'`; rm -rf ../other", false},
		{"echo `#x'\\\\`; rm -rf ../repo", true},
		{"echo `#x'\\\\`; rm -rf ../other", false},
		{"rm -rf { ..\\/repo", true},
		{"rm -rf { ..\\/other", false},
		{"rm -rf } ..\\/repo", true},
		{"rm -rf } ..\\/other", false},
		{"rm { -rf ..\\/repo", true},
		{"rm { -rf ..\\/other", false},
		{"{ rm -rf ..\\/repo; }", true},
		{"{ rm -rf ..\\/other; }", false},
		{"if true; then { rm -rf ..\\/repo; }; fi", true},
		{"if true; then { rm -rf ..\\/other; }; fi", false},
		{"function f { rm -rf ..\\/repo; }; f", true},
		{"function f { rm -rf ..\\/other; }; f", false},
		{"coproc { rm -rf ..\\/repo; }", true},
		{"coproc { rm -rf ..\\/other; }", false},
		{"time -p { rm -rf ..\\/repo; }", true},
		{"time -p { rm -rf ..\\/other; }", false},
		{"echo `{ rm -rf ..\\/repo; }`", true},
		{"echo `{ rm -rf ..\\/other; }`", false},
		{"rm -rf 2\u003e\u00261 ..\\/repo", true},
		{"rm -rf 2\u003e\u00261 ..\\/other", false},
		{"rm -rf ..\\/repo\u003e/dev/null", true},
		{"rm -rf ..\\/other\u003e/dev/null", false},
		{"rm -rf ..\\/repo \u0026\u003e/dev/null", true},
		{"rm -rf ..\\/other \u0026\u003e/dev/null", false},
		{"rm -rf ..\\/repo \u003e\u00262", true},
		{"rm -rf ..\\/other \u003e\u00262", false},
		{"rm -rf ..\\/repo\u003c\u003cEOF\nx\nEOF", true},
		{"rm -rf ..\\/other\u003c\u003cEOF\nx\nEOF", false},
		{"X=../repo\necho a\n# `rm zk3q\nr\\m -rf $X", true},
		{"echo x # rm -rf {SLOT}", false},
		{"cat \u003c\u003cEOF\n$'x\\'\nEOF\nrm -rf ../repo\\\n; # '", true},
		{"sh -c 'r\\\nm -rf ../../zk3q'", true},
		{"sh -c 'r\\\nm -rf ../../other'", false},
		{"bash -c 'r\\\nm -rf ../../zk3q'", true},
		{"bash -c 'r\\\nm -rf ../../other'", false},
		{"eval 'r\\\nm -rf ../../zk3q'", true},
		{"eval 'r\\\nm -rf ../../other'", false},
		{"bash -x -c 'r\\\nm -rf ../../zk3q'", true},
		{"bash -x -c 'r\\\nm -rf ../../other'", false},
		{"sh -ec 'r\\\nm -rf ../../zk3q'", true},
		{"sh -ec 'r\\\nm -rf ../../other'", false},
		{"s\\h -c 'r\\\nm -rf ../../zk3q'", true},
		{"s\\h -c 'r\\\nm -rf ../../other'", false},
		{"s'h' -c 'r\\\nm -rf ../../zk3q'", true},
		{"s'h' -c 'r\\\nm -rf ../../other'", false},
		{"e\\val 'r\\\nm -rf ../../zk3q'", true},
		{"e\\val 'r\\\nm -rf ../../other'", false},
		{"/bin/s\\h -c 'r\\\nm -rf ../../zk3q'", true},
		{"/bin/s\\h -c 'r\\\nm -rf ../../other'", false},
		{"$'s\\x68' -c 'r\\\nm -rf ../../zk3q'", true},
		{"env sh -c 'r\\\nm -rf ../../zk3q'", true},
		{"env sh -c 'r\\\nm -rf ../../other'", false},
		{"nohup bash -c 'r\\\nm -rf ../../zk3q'", true},
		{"nohup bash -c 'r\\\nm -rf ../../other'", false},
		{"xargs sh -c 'r\\\nm -rf ../../zk3q'", true},
		{"xargs sh -c 'r\\\nm -rf ../../other'", false},
		{"su -c 'r\\\nm -rf ../../zk3q'", true},
		{"su -c 'r\\\nm -rf ../../other'", false},
		{"su --command 'rm -rf ../repo' root", true},
		{"su --session-command 'rm -rf ../repo' root", true},
		{"su --com='rm -rf ../repo' root", true},
		{"su --se 'rm -rf ../repo' root", true},
		{"bash -c 2\u003e/dev/null 'rm -rf ../repo'", true},
		{"bash -c 2\u003e/dev/null 'rm -rf ../other'", false},
		{"bash -c -e 'rm -rf ../repo'", true},
		{"bash -c -e 'rm -rf ../other'", false},
		{"bash -c -- 'rm -rf ../repo'", true},
		{"bash -c -- 'rm -rf ../other'", false},
		{"eval -- 'rm -rf ../repo'", true},
		{"eval -- 'rm -rf ../other'", false},
		{"bash -c $'rm\\t-rf\\t../repo'", true},
		{"eval $'rm\\t-rf\\t../repo'", true},
		{"sh -c $'echo a\\nrm -rf ../repo'", true},
		{"sudo -u root bash -c 'rm -rf ../repo'", true},
		{"sudo -u root bash -c 'rm -rf ../other'", false},
		{"timeout 5 sh -c 'rm -rf ../repo'", true},
		{"timeout 5 sh -c 'rm -rf ../other'", false},
		{"bash -c '\u003c\u003c\u003cignored; rm -rf ../repo'", true},
		{"timeout 5s bash -c 'rm -rf ../repo'", true},
		{"timeout 5s bash -c 'rm -rf ../other'", false},
		{"timeout 0.5 sh -c 'rm -rf ../repo'", true},
		{"timeout 0.5 sh -c 'rm -rf ../other'", false},
		{"bash -c -O nullglob 'rm -rf ../repo'", true},
		{"bash -c -O nullglob 'rm -rf ../other'", false},
		{"bash -co posix 'rm -rf ../repo'", true},
		{"bash -co posix 'rm -rf ../other'", false},
		{"bash -oc posix 'rm -rf ../repo'", true},
		{"bash -cO nullglob 'rm -rf ../repo'", true},
		{"bash -cO nullglob 'rm -rf ../other'", false},
		{"bash +c 'rm -rf ../repo'", true},
		{"bash +c 'rm -rf ../other'", false},
		{"bash -c -- '-missing; rm -rf ../repo'", true},
		{"bash -c -- '-missing; rm -rf ../other'", false},
		{"eval -- '+echo; rm -rf ../repo'", true},
		{"eval -- '+echo; rm -rf ../other'", false},
		{"eval -- '-missing; rm -rf ../repo'", true},
		{"eval -- '-missing; rm -rf ../other'", false},
		{"eval 2\u003e/dev/null 'rm -rf ../repo'", true},
		{"eval 2\u003e/dev/null 'rm -rf ../other'", false},
		{"eval 2\u003e /dev/null -- rm -rf ../repo", true},
		{"eval 2\u003e /dev/null -- rm -rf ../other", false},
		{"bash --rcfile /dev/null -c 'rm -rf ../repo'", true},
		{"bash --init-file /dev/null -c 'rm -rf ../repo'", true},
		{"bash --norc -c 'rm -rf ../repo'", true},
		{"bash --norc -c 'rm -rf ../other'", false},
		{"bash -n +o noexec -c 'rm -rf ../repo'", true},
		{"bash -n +o noexec -c 'rm -rf ../other'", false},
		{"zsh -oshwordsplit -c 'rm -rf ../repo'", true},
		{"bash -c \u0026\u003e/dev/null 'rm -rf ../repo'", true},
		{"bash -c \u0026\u003e/dev/null 'rm -rf ../other'", false},
		{"bash -c \u003e'log file' 'rm -rf ../repo'", true},
		{"bash -c \u003e'log file' 'rm -rf ../other'", false},
		{"eval '+echo; rm -rf ../repo'", true},
		{"eval '+echo; rm -rf ../other'", false},
		{"bash -n +n -c 'rm -rf ../repo'", true},
		{"bash -n +n -c 'rm -rf ../other'", false},
		{"bash -c 'rm -rf .'", true},
		{"bash -c 'rm -rf ./build'", false},
		{"sh -c \"r\\\nm -rf ../../zk3q\"", true},
		{"sh -c 'cd ..'; rm -rf repo", false},
		{"echo sh -c 'rm -rf .'", false},
		{"printf '%s' sh -c 'rm -rf .'", false},
		{"echo bash -c 'rm -rf ../repo'", false},
		{"echo eval 'rm -rf ../repo'", false},
		{"echo su --command 'rm -rf ../repo'", false},
		{"bash -c 'echo hi' rm -rf", false},
		{"echo 'r\\\nm -rf ../../zk3q'", false},
		{"rm -rf '.\\\n' sh", false},
		{"sh -c \"sh -c \\\"sh -c \\\\\\\"rm -rf .\\\\\\\"\\\"\"", true},
		{"sh -c \"sh -c \\\"sh -c \\\\\\\"rm -rf ./build\\\\\\\"\\\"\"", false},
		{"git worktree remove {CHECKOUT}", true},
		{"git worktree remove --force {CHECKOUT}", true},
		{"git -C /tmp worktree remove {CHECKOUT}", true},
		{"git -c core.x=y worktree remove {CHECKOUT}", true},
		{"git worktree remove {SLOT}", true},
		{"sudo git worktree remove -f {CHECKOUT}", true},
		{"git worktree remove .", true},
		{"git -C {SLOT} worktree remove ./repo", true},
		{"git status", false},
		{"git worktree list", false},
		{"git worktree prune", false},
		{"git worktree remove /some/other/place", false},
		{"git worktree remove {OTHER}", false},
		{"git -C {OTHER} status", false},
		{"git worktree remove ''", false},
		{"git worktree add {OTHER}", false},
		{"rm -rf \"$X\" \u0026\u0026 echo cleaning zk3q", true},
		{"rm {CHECKOUT}", false},
		{"rm -rf \"$X\" \u0026\u0026 echo {WORKTREES}", true},
		{"echo zk3q", false},
		{"ls {SLOT}", false},
		{"rm -rf ./build", false},
		{"rd {CHECKOUT}", false},
		{"Remove-Item -Recurse -LiteralPath {SLOT}", false},
		{"REMOVE-ITEM {CHECKOUT}", false},
		{"Remove-Item .", false},
		{"rd .", false},
		{"Remove-Item -Recurse .", false},
		{"eraſe {SLOT}", false},
		{"git worKtree remove {CHECKOUT}", true},
		{"echo hi\nrm -rf .", true},
		{"echo hi\nrm -rf ./build", false},
		{"cd ..\nrm -rf repo", true},
		{"cd /tmp\nrm -rf {SLOT}", true},
		{"cd /tmp\nrm -rf {OTHER}", false},
		{"sleep 1 \u0026 rm -rf .", true},
		{"sleep 1 \u0026 rm -rf ./build", false},
		{"(rm -rf .)", true},
		{"(rm -rf ./build)", false},
		{"echo $(rm -rf .)", true},
		{"echo $(rm -rf ./build)", false},
		{"{ rm -rf .; }", true},
		{"{ rm -rf ./build; }", false},
		{"{\\\n rm -rf ../repo; }", true},
		{"{\\\n rm -rf ../other; }", false},
		{"cleanup() { rm -rf .; }", true},
		{"cleanup() { rm -rf ./build; }", false},
		{"(cd /tmp)\nrm -rf ../repo", true},
		{"(cd /tmp \u0026\u0026 rm -rf ./build)", false},
		{"git worktree remove \\\n.", true},
		{"git worktree list \\\n.", false},
		{"rm -rf --no-preserve-root /", true},
		{"rm -rf --no-preserve-root {OTHER}", false},
		{"rmdir /", true},
		{"rmdir {OTHER}", false},
		{"cat \u003e clean.sh \u003c\u003c'EOF'\nrm -rf ./build\nEOF", false},
		{"bash -c \"rm -rf {SLOT}\"", true},
		{"sh -c 'rm -rf {CHECKOUT}'", true},
		{"echo \"rm -rf {SLOT}\"", false},
		{"bash -c \"rm -rf {OTHER}\"", false},
		{"echo \"rm -rf ./build\"", false},
		{"rm -rf .{cache,local}", true},
		{"find . -exec ls {} +", false},
		{"rm -rf .\\\n{\\\ncache,local}", true},
		{"bash -c \"$(printf 'rm -rf ../repo')\"", true},
		{"bash -c \"$x\"", true},
		{"sh -c \"`cat f`\"", true},
		{"sudo bash -c \"$X\"", true},
		{"su -c \"$X\" root", true},
		{"su -c'$X' root", true},
		{"su --command='$X' root", true},
		{"eval \"$(printf 'rm -rf ../repo')\"", true},
		{"eval $X", true},
		{"source \u003c(printf 'rm -rf ../repo')", true},
		{". \u003c(cat f)", true},
		{"source \"$F\"", true},
		{"printf 'rm -rf ../repo' | bash", true},
		{"cat f | sh", true},
		{"bash \u003c\u003c\u003c \"$(printf 'rm -rf ../repo')\"", true},
		{"bash -c 'bash -c \"$(printf x)\"'", true},
		{"bash -c 'echo $1' x y", false},
		{"bash -c \"echo \\$HOME\"", false},
		{"bash -c 'echo OK'", false},
		{"eval echo ok", false},
		{"echo \"$HOME\"", false},
		{"ls | grep x", false},
		{"bash \u003c\u003cEOF\n$(printf 'rm -rf ../repo')\nEOF", true},
		{"bash \u003c\u003cEOF\n`printf 'rm -rf ../repo'`\nEOF", true},
		{"bash \u003c\u003cEOF\n$X\nEOF", true},
		{"bash \u003c\u003cEOF\necho '$X'\nEOF", true},
		{"sh \u003c\u003c-EOF\n\t$(cat f)\n\tEOF", true},
		{"bash -s \u003c\u003cEOF\n$X\nEOF", true},
		{"bash \u003c\u003cEOF\n$X", true},
		{"0\u003c\u003cEOF bash\n$X\nEOF", true},
		{"bash \u003c\u003c'EOF'\nprintf hi\nEOF", false},
		{"bash \u003c\u003c'EOF'\necho \"$HOME\"\nEOF", false},
		{"bash \u003c\u003cEOF\nprintf hi\nEOF", false},
		{"bash \u003c\u003cEOF\necho \\$HOME\nEOF", false},
		{"cat \u003c\u003cEOF\n$HOME\nEOF", false},
		{"echo \"$(echo ${x:- #}; echo `rm -rf ../repo`)\"", true},
		{"echo \"$(echo ${x:- #}; echo `rm -rf ../other`)\"", false},
		{"echo \"${x:- #}\"", false},
		{"echo ${x:- #} ok", false},
		{"echo \"$(true)\" '$(rm -rf ../repo)'", false},
		{"echo \"$(true)\" \"$(rm -rf ../repo)\"", true},
		{"cd /tmp; echo \"$(rm -rf ../repo)\"", false},
		{"cd ..; echo \"$(rm -rf repo)\"", true},
		{"bash -c 'echo large' 'rm -rf ../repo'", false},
		{"bash -c 'echo OK; true' 'rm -rf ../repo'", false},
		{"bash -c 'echo cargo' 'rm -rf ../repo'", false},
		{"bash -c 'eval \"$1\"' _ 'rm -rf ../repo'", true},
		{"bash -c '\"$@\"' _ rm -rf ../repo", true},
		{"echo \"${x:-$(rm -rf ../repo)}\"", true},
		{"echo \"${x:-$(rm -rf ../other)}\"", false},
		{"echo \"${x:-$(true)}\"", false},
		{"echo \"cd /tmp $(rm -rf ../repo)\"", true},
		{"echo \"cd /tmp $(rm -rf ../other)\"", false},
		{"cat \u003c\u003cEOF\nbash -c \"$X\"\nEOF", false},
		{"cat \u003c\u003c'EOF'\nbash -c \"$X\"\nEOF", false},
		{"Y=1 $X -rf ../repo", true},
		{"bash 0\u003c\u003cEOF\n$(printf 'rm -rf ../repo')\nEOF", true},
		{"bash 0\u003c\u003c\u003c\"$(printf 'rm -rf ../repo')\"", true},
		{"eval \u003e '$X' \"$X\"", true},
		{"bash -c '\"$0\" \"$@\"' rm -rf ../repo", true},
		{"printf 'rm -rf ../repo' | bash 3\u003c/dev/null", true},
		{"su -c'rm -rf ../repo'", true},
		{"su -lc'rm -rf ../repo'", true},
		{"su - root -c'rm -rf ../repo'", true},
		{"su -c 'rm -rf ../repo'", true},
		{"su root -c 'rm -rf ../repo'", true},
		{"su -c 'echo a' -c 'rm -rf ../repo' root", true},
		{"su --command='rm -rf ../repo' root", true},
		{"su -lc'sudo rm -rf ../repo'", true},
		{"bash -lc 'rm -rf ../repo'", true},
		{"bash -cx 'rm -rf ../repo'", true},
		{"sh -ec 'rm -rf ../repo'", true},
		{"zsh -fc 'rm -rf ../repo'", true},
		{"su -c 'eval \"$1\"' root 'rm -rf ../repo'", true},
		{"bash -c 'declare -p BASH_ARGV | cut -d\" -f2 | bash' x 'rm -rf ../repo'", true},
		{"su -c 'echo ok' -w '\u003e' -c 'rm -rf ../repo' root", true},
		{"su -c 'echo ok' --whitelist-environment -w -c 'rm -rf ../repo' root", true},
		{"bash -c 2\u003e /dev/null 'rm -rf ../repo'", true},
		{"bash -c {fd}\u003e/dev/null 'rm -rf ../repo'", true},
		{"bash -o posix -c 'rm -rf ../repo'", true},
		{"su -s /bin/sh -c 'rm -rf ../repo' root", true},
		{"su -c'r\\\nm -rf ../../zk3q'", true},
		{"su -lc'rm -rf ../repo' root", true},
		{"bash -c 'echo OK' 'rm -rf ../repo'", false},
		{"sh -c 'echo OK' x 'rm -rf ../repo'", false},
		{"zsh -c 'echo OK' 'rm -rf ../repo'", false},
		{"su -c 'echo ok'", false},
		{"bash -c - 'rm -rf ../repo'", true},
		{"bash script.sh 'rm -rf ../repo'", true},
		{"zsh -c -oshwordsplit 'echo OK' 'rm -rf ../repo'", true},
		{"su --shell /bin/sh 'rm -rf ../repo'", true},
		{"su -c 'echo ok' -- root 'rm -rf ../repo'", true},
	}
}

// TestWorktreeDelCorpus judges every corpus row against the reader.
func TestWorktreeDelCorpus(t *testing.T) {
	r := newDelRig(t)
	fill := strings.NewReplacer("{CHECKOUT}", r.checkout, "{SLOT}", r.slotRoot, "{WORKTREES}", r.worktrees,
		"{OTHER}", r.other, "{HOME}", r.home)
	for _, row := range worktreeDelCorpusRows() {
		cmd := fill.Replace(row.cmd)
		if got := r.verdict(cmd); got.Deny != row.deny {
			t.Errorf("%q: deny=%v, corpus deny=%v (%s)", cmd, got.Deny, row.deny, got.Reason)
		}
	}
	r.intact(t)
}
