package linkage

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"testing"

	"github.com/thisisjun786/codex-relay-workflow/internal/contract"
	"github.com/thisisjun786/codex-relay-workflow/internal/relay/registry"
	"github.com/thisisjun786/codex-relay-workflow/internal/relay/store"
)

// Python oracle generated by testdata/gen_coordination.py using the shipped Python source.
type coordinationOracle struct {
	Exact []struct {
		Input  any    `json:"input"`
		Output string `json:"output"`
		Reason string `json:"reason"`
		Detail string `json:"detail"`
	} `json:"exact"`
	IDs       []string         `json:"ids"`
	Record    map[string]any   `json:"record"`
	Error     map[string]any   `json:"error"`
	Conflicts []map[string]any `json:"conflicts"`
}

func coordinationFixture(t *testing.T) coordinationOracle {
	t.Helper()
	b, err := os.ReadFile("testdata/python_coordination.json")
	if err != nil {
		t.Fatal(err)
	}
	var v coordinationOracle
	if err = json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func Test26_CCL1_existing_linkage_commands_are_registered(t *testing.T) {
	// CCL-1 is split by owner: merge-turn commands belong to 26B, capacity/region to 27.
	for _, name := range []string{"linkage-bind", "linkage-supervise", "linkage-peer", "linkage-attach", "linkage-outstanding", "linkage-completion", "linkage-handover", "linkage-directive", "linkage-settle", "linkage-down", "linkage-up", "linkage-counterpart"} {
		var stdout, stderr byteBuffer
		code := registry.ExecuteAs(context.Background(), "codex-session-relay", []string{name, "--help"}, &stdout, &stderr, nil)
		if code != 0 || stdout.Len() == 0 || stderr.Len() != 0 {
			t.Errorf("%s: code=%d stdout=%q stderr=%q", name, code, stdout.String(), stderr.String())
		}
	}
}

type byteBuffer struct{ data []byte }

func (b *byteBuffer) Write(p []byte) (int, error) { b.data = append(b.data, p...); return len(p), nil }
func (b *byteBuffer) Len() int                    { return len(b.data) }
func (b *byteBuffer) String() string              { return string(b.data) }

func Test26_CoordinationExact_matches_python_source(t *testing.T) {
	for _, v := range coordinationFixture(t).Exact {
		input, ok := v.Input.(string)
		if !ok {
			continue
		} // Go callers provide strings; Python's dynamic type rejection is internal.
		got, err := registry.CoordinationExact(input, "a target")
		if v.Reason == "" {
			if err != nil || got != v.Output {
				t.Errorf("%q: got %q, %v; want %q", input, got, err, v.Output)
			}
			continue
		}
		var refused *store.RefusedError
		if !errors.As(err, &refused) || refused.Reason != v.Reason || refused.Detail != v.Detail {
			t.Errorf("%q: got %v; want %s %q", input, err, v.Reason, v.Detail)
		}
	}
}

func Test26_CoordinationID_matches_python_source(t *testing.T) {
	oracle := coordinationFixture(t)
	for i, fields := range [][]string{{"owner/repo", "dev"}, {"owner", "repo|dev"}, {"é", "dev"}} {
		got := registry.CoordinationID("mrg", fields...)
		if got != oracle.IDs[i] {
			t.Errorf("%d: got %q want %q", i, got, oracle.IDs[i])
		}
	}
}

func Test26_CoordinationRefusal_matches_python_record_and_error(t *testing.T) {
	oracle := coordinationFixture(t)
	r := registry.CoordinationRefusal{Reason: contract.RefusalUnregisteredScope, Detail: "target must not contain '|'", Domain: registry.DomainMergeTarget, Subject: "dev", Challenger: "other"}
	if got := decode(t, r.Record()); !reflect.DeepEqual(got, oracle.Record) {
		t.Errorf("record: got %v want %v", got, oracle.Record)
	}
	var refused *store.RefusedError
	if !errors.As(r.Error(), &refused) || refused.Reason != oracle.Error["reason"] || refused.Detail != oracle.Error["detail"] {
		t.Errorf("error: %v want %v", r.Error(), oracle.Error)
	}
}

func Test26_CoordinationConflicts_upsert_and_read_match_python(t *testing.T) {
	w := newWorld(t)
	r := registry.CoordinationRefusal{Reason: contract.RefusalUnregisteredScope, Detail: "target must not contain '|'", Domain: registry.DomainMergeTarget, Subject: "dev", Challenger: "other"}
	if err := w.r.RecordCoordinationRefusal(w.ctx, r, "2023-11-14T22:13:20Z"); err == nil {
		t.Fatal("refusal was not returned")
	}
	r.Detail = "new detail"
	if err := w.r.RecordCoordinationRefusal(w.ctx, r, "2023-11-14T22:13:21Z"); err == nil {
		t.Fatal("refusal was not returned")
	}
	rows, err := w.r.CoordinationConflicts(w.ctx, registry.DomainMergeTarget, "dev")
	if err != nil {
		t.Fatal(err)
	}
	got := make([]any, 0, len(rows))
	for _, row := range rows {
		got = append(got, decode(t, row))
	}
	oracle := coordinationFixture(t)
	expected := make([]any, 0, len(oracle.Conflicts))
	for _, row := range oracle.Conflicts {
		expected = append(expected, row)
	}
	if !reflect.DeepEqual(got, expected) {
		t.Errorf("got %v want %v", got, expected)
	}
}
