//go:build dev

package cxccorpus

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os/exec"
	"path/filepath"
)

// Constants is contract/schema/cxc/injected-text.json: contract K5's exported text constants,
// the model-facing directives and markers the hooks inject, frozen as data. Rendered text (stage
// directives, Stop reasons, affordances) is in the hook fixtures; these are the constants it is
// built from.
const Constants = SchemaDir + "/injected-text.json"

// ConstantModules are the dist modules contracts.md K5 names. None runs a CLI when imported: the
// two entrypoints among them (spawn-attach-hook, fallback-dispatch-cli) start only when they are
// process.argv[1], which `node -e` leaves unset.
var ConstantModules = []string{
	"components/pabcd-state/dist/freeze.js",
	"components/pabcd-state/dist/minds.js",
	"components/pabcd-state/dist/hook.js",
	"components/pabcd-state/dist/goal-gate.js",
	"components/pabcd-state/dist/agent-thread-permissions.js",
	"components/pabcd-state/dist/codexclaw-dir.js",
	"components/pabcd-state/dist/worktree-guard.js",
	"components/subagent-config/dist/spawn-attach-hook.js",
	"components/subagent-config/dist/final-gate-guard.js",
	"components/subagent-config/dist/fallback-dispatch-cli.js",
	"components/subagent-config/dist/dispatch-card.js",
	"components/config-guard/dist/multi-agent-v2.js",
	"components/config-guard/dist/self-heal.js",
	"components/cxc-ops/dist/map-affordance.js",
	"components/recall/dist/hook.js",
	"components/bg-wake/dist/hook.js",
}

const constantsScript = `const out = {};
for (const rel of JSON.parse(process.env.CXC_MODULES)) {
  const mod = await import(process.env.CXC_PLUGIN + "/" + rel);
  const kept = {};
  for (const name of Object.keys(mod).sort()) {
    const v = mod[name];
    if (typeof v === "string" || (Array.isArray(v) && v.length > 0 && v.every((x) => typeof x === "string"))) kept[name] = v;
  }
  out[rel] = kept;
}
process.stdout.write(JSON.stringify(out));
`

// ConstantsFile is the extracted document.
type ConstantsFile struct {
	Description string                                `json:"description"`
	Oracle      string                                `json:"oracle"`
	Modules     map[string]map[string]json.RawMessage `json:"modules"`
}

// ExtractConstants imports the modules in an isolated case root (the same environment as a
// recording) and keeps every exported string and string array, normalised.
func (r *Recorder) ExtractConstants() (ConstantsFile, error) {
	c, err := r.newCase(Scenario{ID: "constants"})
	if c != nil {
		defer func() { _ = removeTree(c.root) }()
	}
	if err != nil {
		return ConstantsFile{}, err
	}
	modules, _ := json.Marshal(ConstantModules)
	plugin := filepath.Join(r.Oracle, "plugins", "codexclaw")
	cmd := exec.Command(r.Node, "--input-type=module", "-e", constantsScript)
	cmd.Dir = filepath.Join(c.root, "ws")
	cmd.Env = append(append([]string{}, c.env...), "CXC_MODULES="+string(modules), "CXC_PLUGIN="+plugin)
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	if err := cmd.Run(); err != nil {
		return ConstantsFile{}, fmt.Errorf("import the modules: %w: %s", err, stderr.String())
	}
	text := r.Rules.NewSession(r.bindings(c)).Text(stdout.String())
	var modulesOut map[string]map[string]json.RawMessage
	if err := json.Unmarshal([]byte(text), &modulesOut); err != nil {
		return ConstantsFile{}, err
	}
	return ConstantsFile{
		Description: "Contract K5: every exported string (or string array) of the modules contracts.md K5 names, as the CXC v0.2.40 oracle exports them, normalised with normalisation.json. These are the injected directives and markers; the CRW side compares them after name-substitution.json, as an explicit exception to contract/README.md's rule that prose is not a contract (decision 12). Generated by `crw-dev cxc constants`.",
		Oracle:      OracleTag + " " + OracleCommit,
		Modules:     modulesOut,
	}, nil
}
