//go:build dev

package cxccorpus

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// DeclarationFile is contract/schema/cxc/hook-declarations.json (contract K1): every hook
// registration plugin.json lists, in manifest order, with its command split into the entry file
// and arguments the recorder runs.
type DeclarationFile struct {
	Description string        `json:"description"`
	Oracle      string        `json:"oracle"`
	Legs        []Declaration `json:"legs"`
}

var hookCommand = regexp.MustCompile(`^node "\$\{PLUGIN_ROOT\}/([^"]+)"((?: [a-z-]+)*)$`)

// ExtractDeclarations reads the oracle's manifest and hook files. A file with one registration
// names its leg after itself; a file with several adds .<event-in-kebab-case>.
func ExtractDeclarations(oracle string) (DeclarationFile, error) {
	plugin := filepath.Join(oracle, "plugins", "codexclaw")
	var manifest struct {
		Hooks []string `json:"hooks"`
	}
	if err := readJSON(filepath.Join(plugin, ".codex-plugin", "plugin.json"), &manifest); err != nil {
		return DeclarationFile{}, err
	}
	out := DeclarationFile{
		Description: "Every hook registration of CXC v0.2.40 (plugins/codexclaw/.codex-plugin/plugin.json hooks, in manifest order), contract K1. leg is the corpus name a fixture step's hook field uses; entry and args are the declared command with ${PLUGIN_ROOT} removed. Generated by `crw-dev cxc declarations`; matchers, timeouts and statusMessages are byte-identical to the oracle.",
		Oracle:      OracleTag + " " + OracleCommit,
	}
	for _, rel := range manifest.Hooks {
		var file struct {
			Hooks map[string][]struct {
				Matcher string `json:"matcher"`
				Hooks   []struct {
					Type          string `json:"type"`
					Command       string `json:"command"`
					Timeout       int    `json:"timeout"`
					StatusMessage string `json:"statusMessage"`
				} `json:"hooks"`
			} `json:"hooks"`
		}
		if err := readJSON(filepath.Join(plugin, rel), &file); err != nil {
			return out, err
		}
		stem := strings.TrimSuffix(filepath.Base(rel), ".json")
		var events []string
		raw, _ := os.ReadFile(filepath.Join(plugin, rel))
		// Keep the file's own event order (map iteration would not).
		for _, m := range regexp.MustCompile(`"(SessionStart|UserPromptSubmit|Stop|PreToolUse|PostToolUse|PostCompact|SubagentStop|PermissionRequest)"\s*:`).FindAllStringSubmatch(string(raw), -1) {
			events = append(events, m[1])
		}
		count := 0
		for _, event := range events {
			count += len(file.Hooks[event])
		}
		for _, event := range events {
			for _, group := range file.Hooks[event] {
				for _, hook := range group.Hooks {
					m := hookCommand.FindStringSubmatch(hook.Command)
					if m == nil || hook.Type != "command" {
						return out, fmt.Errorf("%s: unrecognised hook command %q", rel, hook.Command)
					}
					leg := stem
					if count > 1 {
						leg = stem + "." + kebab(event)
					}
					out.Legs = append(out.Legs, Declaration{
						Leg: leg, File: strings.TrimPrefix(rel, "./"), Event: event, Matcher: group.Matcher,
						Command: hook.Command, Entry: m[1], Args: strings.Fields(m[2]),
						Timeout: hook.Timeout, Status: hook.StatusMessage,
					})
				}
			}
		}
	}
	return out, nil
}

func kebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String()
}

func readJSON(path string, into any) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(raw, into); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

// LoadDeclarations reads the committed declarations, keyed by leg.
func LoadDeclarations(root string) (DeclarationFile, map[string]Declaration, error) {
	var file DeclarationFile
	if err := readStrict(filepath.Join(root, Declarations), &file); err != nil {
		return file, nil, err
	}
	byLeg := map[string]Declaration{}
	for _, d := range file.Legs {
		if _, dup := byLeg[d.Leg]; dup {
			return file, nil, fmt.Errorf("%s: leg %q twice", Declarations, d.Leg)
		}
		byLeg[d.Leg] = d
	}
	return file, byLeg, nil
}
