package supervisor

import (
	"bytes"
	"context"
	"github.com/thisisjun786/codex-relay-workflow/internal/relay/evidence"
	"strings"
	"testing"

	"github.com/thisisjun786/codex-relay-workflow/internal/relay/store"
)

const captureAt21 = "2023-11-14T22:13:20.000000+00:00"

func captureStaged21(t *testing.T, c *Channel, s *store.Store) (Obligation, string) {
	t.Helper()
	var event string
	if err := s.DB.QueryRow("SELECT event_id FROM events ORDER BY rowid DESC LIMIT 1").Scan(&event); err != nil {
		t.Fatal(err)
	}
	o, err := c.FromEvent(context.Background(), event)
	if err != nil || o == nil {
		t.Fatalf("obligation: %v %v", o, err)
	}
	result, err := c.Stage(context.Background(), *o, "", captureAt21)
	if err != nil {
		t.Fatal(err)
	}
	return *o, result["messageId"].(string)
}

// Each Python capture starts its token sequence at zero. The Go replay draws the
// same eight bytes per attempt, without changing the production random source.
func captureTokens21(t *testing.T) {
	t.Helper()
	previous := tokenSource
	tokenSource = &captureTokenReader21{}
	t.Cleanup(func() { tokenSource = previous })
}

type captureTokenReader21 struct{ next uint64 }

func (r *captureTokenReader21) Read(p []byte) (int, error) {
	for i := range p {
		p[i] = byte(r.next >> (8 * (len(p) - 1 - i)))
	}
	r.next++
	return len(p), nil
}

func Test24_SCH_21_LiveRecoveredClaim(t *testing.T) {
	captureTokens21(t)
	supervisorMirror(t, "WhatTheReviewFound.test_a_send_interrupted_after_its_claim_is_recovered_rather_than_stranded", "event", func(c *Channel, s *store.Store) []any {
		ctx := context.Background()
		c.clockISO = func() string { return captureAt21 }
		_, id := captureStaged21(t, c, s)
		// Reconstruct the unstarted claim with the production frozen packet renderer.
		row, err := c.Get(ctx, id)
		if err != nil {
			t.Fatal(err)
		}
		packet := Packet(evidence.Dict(evidence.Decode(row.Packet), false))
		request := "sup-" + id[:12] + "-a1"
		token := request + ".0000000000000000"
		message := c.render(packet, request, token)
		now := float64(1700000000)
		lease := now + 300
		_, err = s.DB.ExecContext(ctx, "UPDATE supervisor_messages SET state='sending',attempt_count=1,lease_owner=?,lease_until=?,updated_at=? WHERE message_id=?", "a worker that died", lease, captureAt21, id)
		if err != nil {
			t.Fatal(err)
		}
		_, err = s.DB.ExecContext(ctx, "INSERT INTO supervisor_attempts(request_id,message_id,attempt_no,message,state,send_attempted,retry_safe,record,sent_at,observed_at,delivery_token) VALUES(?,?,1,?,'held_uncertain','unknown',0,?,?,?,?)", request, id, message, evidence.Dumps(map[string]any{"requestId": request, "messageId": id, "attemptNo": 1, "deliveryState": "held_uncertain"}, false, true, false), captureAt21, captureAt21, token)
		if err != nil {
			t.Fatal(err)
		}
		current, err := c.Get(ctx, id)
		if err != nil {
			t.Fatal(err)
		}
		stranded, err := c.Stranded(ctx, lease+1)
		if err != nil {
			t.Fatal(err)
		}
		recovered, err := c.recoverStranded(ctx, current, lease+1)
		if err != nil {
			t.Fatal(err)
		}
		attempt, err := s.SupervisorAttempts(ctx, id)
		if err != nil {
			t.Fatal(err)
		}
		var count int
		if err = s.DB.QueryRowContext(ctx, "SELECT count(*) FROM journal WHERE kind='supervisor_message_released'").Scan(&count); err != nil {
			t.Fatal(err)
		}
		var detail string
		if err = s.DB.QueryRowContext(ctx, "SELECT detail FROM journal WHERE kind='supervisor_message_released'").Scan(&detail); err != nil {
			t.Fatal(err)
		}
		return []any{current.State, stranded[0].MessageID, recovered.State, []any{attempt[0].State, attempt[0].SendAttempted, attempt[0].RetrySafe}, count, strings.Contains(detail, "before the transport started")}
	})
}

// Keep the seam's generated bytes pinned independently from the frozen-message
// comparison: changing the token prefix must be observable by the mirror.
func Test24_SCH_21_TokenSource(t *testing.T) {
	captureTokens21(t)
	b := make([]byte, 8)
	if _, err := tokenSource.Read(b); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(b, make([]byte, 8)) {
		t.Fatalf("first token: %x", b)
	}
	if _, err := tokenSource.Read(b); err != nil {
		t.Fatal(err)
	}
	if b[7] != 1 {
		t.Fatalf("second token: %x", b)
	}
}
